#!/usr/bin/env python3
"""Detect changed schema fragments and scaffold per-table migrations.

Edit schema/<module>/<table>.sql, then run this. For every fragment that is NEW or
CHANGED since the last run, it writes ONE migration that names only that table —
unchanged tables produce nothing and are never touched. New tables are seeded with
their full CREATE; changed tables get an ALTER scaffold with the column-level diff
embedded as comments, which you complete with data-preserving ALTERs
(ADD / RENAME / DROP / ALTER COLUMN). Then it previews and pushes only after you
confirm.

State lives in schema/.snapshots/ — the shape each fragment had when its last
migration was generated. That snapshot is how "unchanged -> do nothing" is decided,
and it is updated the moment a migration is generated, so re-running without an
edit produces nothing (no duplicate migrations).

Usage:
    python supabase/scripts/sync_schema.py            # detect -> generate -> review -> prompt to push
    python supabase/scripts/sync_schema.py --status   # only report what changed; generate nothing
    python supabase/scripts/sync_schema.py --no-push   # generate + review, never push
    python supabase/scripts/sync_schema.py --yes       # don't prompt; push if there is anything pushable

A changed table's migration starts as a scaffold containing a TODO marker; the push
step refuses to run while any migration still has that marker, so you can't push an
unfinished ALTER by accident.
"""
from __future__ import annotations

import difflib
import subprocess
import sys
from pathlib import Path

# gen_migration sits next to this file; reuse its monotonic-timestamp logic.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_migration import _next_timestamp  # noqa: E402

SUPABASE_DIR = Path(__file__).resolve().parent.parent
SCHEMA_DIR = SUPABASE_DIR / "schema"
SNAPSHOT_DIR = SCHEMA_DIR / ".snapshots"
MIGRATIONS_DIR = SUPABASE_DIR / "migrations"
TODO_MARKER = "-- TODO:"


# --- discovery -------------------------------------------------------------

def _fragments() -> list[tuple[str, str, Path]]:
    """(module, table, path) for every schema/<module>/<table>.sql (skips dotdirs)."""
    found = []
    for module_dir in sorted(SCHEMA_DIR.iterdir()):
        if not module_dir.is_dir() or module_dir.name.startswith("."):
            continue
        for path in sorted(module_dir.glob("*.sql")):
            found.append((module_dir.name, path.stem, path))
    return found


def _snapshot_path(module: str, table: str) -> Path:
    return SNAPSHOT_DIR / module / f"{table}.sql"


def _classify(module: str, table: str, path: Path) -> str:
    snap = _snapshot_path(module, table)
    if not snap.exists():
        return "new"
    if snap.read_text(encoding="utf-8") != path.read_text(encoding="utf-8"):
        return "changed"
    return "unchanged"


def _removed_tables() -> list[tuple[str, str]]:
    """Snapshots with no matching fragment — a table the user deleted from schema/."""
    live = {(m, t) for m, t, _ in _fragments()}
    gone = []
    if SNAPSHOT_DIR.exists():
        for snap in sorted(SNAPSHOT_DIR.glob("*/*.sql")):
            key = (snap.parent.name, snap.stem)
            if key not in live:
                gone.append(key)
    return gone


# --- migration bodies ------------------------------------------------------

def _new_body(module: str, table: str, fragment: str) -> str:
    header = (
        f"-- create_{table}\n"
        f"-- Generated by scripts/sync_schema.py (new table from schema/{module}/{table}.sql)\n\n"
    )
    return header + fragment.strip() + "\n"


def _changed_body(module: str, table: str, old: str, new: str) -> str:
    diff = difflib.unified_diff(
        old.splitlines(), new.splitlines(),
        fromfile=f"schema/{module}/{table}.sql (last migrated)",
        tofile=f"schema/{module}/{table}.sql (now)",
        lineterm="",
    )
    diff_block = "\n".join(f"-- {line}" for line in diff)
    return (
        f"-- alter_{table}\n"
        f"-- Generated by scripts/sync_schema.py (CHANGED table — fill in the ALTERs)\n"
        f"--\n"
        f"-- Column-level diff of schema/{module}/{table}.sql since its last migration:\n"
        f"{diff_block}\n"
        f"--\n"
        f"-- Translate the diff above into data-preserving statements, then DELETE the\n"
        f"-- TODO line below (push is blocked while it remains). Examples:\n"
        f"--   alter table public.{table} add column <col> <type>;\n"
        f"--   alter table public.{table} rename column <old> to <new>;\n"
        f"--   alter table public.{table} drop column <col>;\n"
        f"--   alter table public.{table} alter column <col> type <type>;\n"
        f"{TODO_MARKER} write the ALTER statement(s) for the diff above.\n"
    )


def _write_migration(name: str, body: str) -> Path:
    target = MIGRATIONS_DIR / f"{_next_timestamp()}_{name}.sql"
    MIGRATIONS_DIR.mkdir(parents=True, exist_ok=True)
    target.write_text(body, encoding="utf-8")
    return target


def _save_snapshot(module: str, table: str, content: str) -> None:
    snap = _snapshot_path(module, table)
    snap.parent.mkdir(parents=True, exist_ok=True)
    snap.write_text(content, encoding="utf-8")


# --- push gate -------------------------------------------------------------

def _migrations_with_todo() -> list[str]:
    return sorted(
        p.name for p in MIGRATIONS_DIR.glob("*.sql")
        if TODO_MARKER in p.read_text(encoding="utf-8")
    )


def _run_supabase(args: list[str]) -> int:
    try:
        return subprocess.call(["supabase", *args], cwd=SUPABASE_DIR)
    except FileNotFoundError:
        print("error: the `supabase` CLI is not on PATH — install it to push.", file=sys.stderr)
        return 1


# --- main ------------------------------------------------------------------

def main(argv: list[str]) -> int:
    flags = set(argv)
    status_only = "--status" in flags
    no_push = "--no-push" in flags
    assume_yes = "--yes" in flags

    fragments = _fragments()
    classified = [(m, t, p, _classify(m, t, p)) for m, t, p in fragments]
    new = [(m, t, p) for m, t, p, c in classified if c == "new"]
    changed = [(m, t, p) for m, t, p, c in classified if c == "changed"]
    removed = _removed_tables()

    print("Schema status:")
    for m, t, _, c in classified:
        mark = {"new": "+ new", "changed": "~ changed", "unchanged": "  unchanged"}[c]
        print(f"  {mark:14} {m}/{t}")
    for m, t in removed:
        print(f"  {'- removed':14} {m}/{t}  (fragment deleted - drop it by hand if intended)")

    if not new and not changed:
        print("\nNo schema changes. Nothing to do.")
        return 0

    if status_only:
        print(f"\n{len(new)} new, {len(changed)} changed. (--status: nothing generated)")
        return 0

    print()
    created: list[Path] = []
    for module, table, path in new:
        content = path.read_text(encoding="utf-8")
        out = _write_migration(f"create_{table}", _new_body(module, table, content))
        _save_snapshot(module, table, content)
        created.append(out)
        print(f"created {out.relative_to(SUPABASE_DIR).as_posix()}  (full CREATE)")

    for module, table, path in changed:
        new_content = path.read_text(encoding="utf-8")
        old_content = _snapshot_path(module, table).read_text(encoding="utf-8")
        out = _write_migration(f"alter_{table}", _changed_body(module, table, old_content, new_content))
        _save_snapshot(module, table, new_content)
        created.append(out)
        print(f"created {out.relative_to(SUPABASE_DIR).as_posix()}  (ALTER scaffold - fill in)")
        print("    --- diff -------------------------------------------------")
        for line in difflib.unified_diff(
            old_content.splitlines(), new_content.splitlines(),
            fromfile="last migrated", tofile="now", lineterm="",
        ):
            print(f"    {line}")
        print("    ----------------------------------------------------------")

    pending_todo = _migrations_with_todo()
    if no_push:
        print("\n--no-push: generated only. Review, complete any TODOs, then `supabase db push`.")
        return 0
    if pending_todo:
        print("\nPush blocked - these migrations still contain a TODO (finish the ALTERs first):")
        for name in pending_todo:
            print(f"    migrations/{name}")
        print("Then run:  supabase db push")
        return 0

    print("\nPreview (supabase db push --dry-run):")
    _run_supabase(["db", "push", "--dry-run"])

    if not assume_yes:
        answer = input("\nPush these migrations to the remote? [y/N] ").strip().lower()
        if answer not in ("y", "yes"):
            print("Aborted. Migrations are staged locally; nothing was pushed.")
            return 0

    print("\nPushing...")
    return _run_supabase(["db", "push"])


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
